import type { Mood } from "@/types";
import { MOODS } from "@/lib/fragrance/families";

/**
 * Scent Tag Engine (architecture §7.2).
 * Each note suggests a few impressions; the seven Mood words (神秘、清新…)
 * double as recommendation moods, the rest are descriptive tags.
 */
export const NOTE_TAGS: Record<string, string[]> = {
  bergamot: ["清新", "活力"],
  grapefruit: ["清新", "活力"],
  lemon: ["清新", "明亮"],
  lime: ["清新", "活力"],
  mandarin: ["清新", "甜美"],
  orange: ["清新", "明亮"],
  neroli: ["清新", "優雅"],
  mint: ["清新", "涼感"],
  "fig-leaf": ["清新", "平靜"],
  "green-notes": ["清新", "自然"],
  rhubarb: ["清新", "酸甜"],
  pine: ["平靜", "自然"],
  "sea-notes": ["清新", "侵略性"],
  calone: ["清新", "侵略性"],
  "sea-salt": ["清新", "侵略性"],
  flint: ["侵略性", "成熟"],
  lavender: ["平靜", "成熟"],
  geranium: ["成熟", "清新"],
  rosemary: ["清新", "自然"],
  sage: ["平靜", "自然"],
  juniper: ["清新", "平靜"],
  jasmine: ["誘人", "優雅"],
  rose: ["優雅", "浪漫", "誘人"],
  iris: ["優雅", "平靜", "成熟"],
  violet: ["優雅", "神秘"],
  "lily-of-the-valley": ["清新", "優雅"],
  "orange-blossom": ["誘人", "明亮"],
  freesia: ["清新", "浪漫"],
  "ylang-ylang": ["誘人", "濃郁"],
  pineapple: ["活力", "侵略性"],
  blackcurrant: ["活力", "酸甜"],
  apple: ["清新", "活力"],
  pear: ["清新", "甜美"],
  peach: ["甜美", "誘人"],
  litchi: ["甜美", "誘人"],
  melon: ["清新", "甜美"],
  fig: ["溫暖", "甜美"],
  oakmoss: ["成熟", "平靜"],
  pepper: ["侵略性", "活力"],
  "pink-pepper": ["活力", "誘人"],
  "sichuan-pepper": ["侵略性", "活力"],
  ginger: ["溫暖", "活力"],
  nutmeg: ["溫暖", "成熟"],
  cardamom: ["溫暖", "神秘"],
  clove: ["溫暖", "濃郁"],
  cedar: ["平靜", "成熟"],
  sandalwood: ["溫暖", "平靜", "成熟"],
  vetiver: ["成熟", "平靜"],
  patchouli: ["沉穩", "平靜", "成熟"],
  "guaiac-wood": ["溫暖", "神秘"],
  rosewood: ["溫暖", "優雅"],
  oud: ["神秘", "成熟", "濃郁"],
  papyrus: ["神秘", "平靜"],
  amber: ["溫暖", "神秘", "誘人"],
  ambroxan: ["侵略性", "清新"],
  labdanum: ["神秘", "溫暖"],
  incense: ["神秘", "平靜"],
  elemi: ["神秘", "清新"],
  opoponax: ["神秘", "溫暖"],
  benzoin: ["溫暖", "甜美"],
  "peru-balsam": ["溫暖", "甜美"],
  vanilla: ["溫暖", "甜美", "誘人"],
  tonka: ["溫暖", "甜美"],
  coffee: ["誘人", "神秘"],
  "bitter-almond": ["甜美", "神秘"],
  licorice: ["神秘", "甜美"],
  chestnut: ["溫暖", "甜美"],
  coconut: ["溫暖", "甜美"],
  musk: ["誘人", "平靜"],
  "white-musk": ["平靜", "乾淨"],
  ambrette: ["誘人", "平靜"],
  ambergris: ["神秘", "成熟"],
  cashmeran: ["溫暖", "平靜"],
  "cashmere-wood": ["溫暖", "平靜"],
  leather: ["侵略性", "成熟", "神秘"],
  birch: ["侵略性", "神秘"],
  "iso-e-super": ["神秘", "侵略性"],
  aldehydes: ["優雅", "侵略性"],
  hinoki: ["平靜", "沉穩", "乾燥"],
  tea: ["平靜", "清新"],
  "black-tea": ["平靜", "溫暖"],
  basil: ["清新", "綠意"],
  petitgrain: ["清新", "明朗"],
  "blood-orange": ["清新", "酸甜"],
  "bitter-orange": ["清新", "明朗"],
  watermelon: ["清新", "活力"],
  tuberose: ["誘人", "濃郁"],
  peony: ["浪漫", "優雅"],
  frankincense: ["神秘", "平靜", "深邃"],
  saffron: ["神秘", "誘人", "辛辣"],
  cinnamon: ["溫暖", "辛辣"],
  rum: ["微醺", "溫暖", "誘人"],
  whisky: ["微醺", "成熟"],
  pistachio: ["可口", "溫暖"],
  hazelnut: ["可口", "溫暖"],
  caramel: ["甜美", "療癒"],
  rice: ["療癒", "平靜"],
  "soy-milk": ["療癒", "溫潤"],
  pumpkin: ["溫潤", "療癒"],
  butter: ["溫潤", "可口"],
  seaweed: ["清涼", "微鹹"],
  ink: ["清冷", "侵略性"],
  metallic: ["清冷", "俐落", "侵略性"],
  // notes added with An's brand product list (data/catalogue.ts, 2026-10-07)
  citrus: ["清新", "活力"],
  ivy: ["清新", "平靜"],
  "bay-leaf": ["清新", "成熟"],
  myrtle: ["清新", "平靜"],
  hyacinth: ["清新", "優雅"],
  marigold: ["溫暖", "活力"],
  lily: ["優雅", "清新"],
  gardenia: ["誘人", "優雅"],
  magnolia: ["優雅", "清新"],
  tulip: ["優雅", "平靜"],
  bluebell: ["清新", "平靜"],
  "peach-blossom": ["甜美", "浪漫"],
  blackberry: ["甜美", "活力"],
  strawberry: ["甜美", "活力"],
  redcurrant: ["活力", "清新"],
  quince: ["甜美", "清新"],
  plum: ["甜美", "誘人"],
  persimmon: ["甜美", "溫潤"],
  sapodilla: ["甜美", "溫潤"],
  grapevine: ["清新", "活力"],
  moss: ["成熟", "神秘"],
  cumin: ["溫暖", "侵略性"],
  cypress: ["清新", "平靜"],
  oak: ["成熟", "平靜"],
  teak: ["溫暖", "成熟"],
  myrrh: ["神秘", "深邃"],
  tobacco: ["成熟", "溫暖", "侵略性"],
  honey: ["甜美", "溫暖"],
  beeswax: ["溫暖", "溫潤"],
  cherry: ["甜美", "誘人"],
  akigalawood: ["清新", "成熟"],
  hibiscus: ["清新", "甜美"],
  water: ["清新", "平靜"],
  driftwood: ["平靜", "清新"],
  "clary-sage": ["平靜", "清新"],
  chamomile: ["療癒", "平靜"],
  cypriol: ["神秘", "成熟"],
  "blond-wood": ["溫暖", "平靜"],
  dill: ["清新", "活力"],
  raspberry: ["甜美", "活力"],
  anise: ["溫暖", "甜美"],
  "white-florals": ["優雅", "清新"],
  champagne: ["活力", "優雅"],
  cucumber: ["清新", "清涼"],
  amyris: ["溫暖", "平靜"],
  eucalyptus: ["清新", "清涼"],
  mimosa: ["甜美", "溫柔"],
  angelica: ["清新", "平靜"],
  "salty-mineral": ["清冷", "清新"],
  "paw-accord": ["溫暖", "療癒"],
  "salt-accord": ["微鹹", "清新"],
  "dry-amber": ["溫暖", "成熟"],
  "burning-wood": ["深邃", "神秘"],
  "green-mandarin": ["清新", "活力"],
  "wood-accord": ["溫暖", "平靜"],
  "posidonia-accord": ["清涼", "微鹹"],
  "infused-vanilla": ["溫暖", "甜美"],
  "almond-milk": ["溫柔", "甜美"],
  "coconut-water": ["清新", "清涼"],
  "mineral-notes": ["清冷", "清新"],
  "volcanic-wood": ["深邃", "溫暖"],
  "dry-wood": ["成熟", "溫暖"],
  perilla: ["清新", "活力"],
  galbanum: ["清新", "侵略性"],
  buchu: ["清新", "活力"],
  sugarcane: ["甜美", "清新"],
  wormwood: ["神秘", "清冷"],
  grass: ["清新", "活力"],
  mahogany: ["成熟", "溫暖"],
  carnation: ["溫柔", "辛香"],
  cyclamen: ["清新", "柔和"],
  frangipani: ["度假", "甜美"],
  hawthorn: ["柔和", "粉感"],
  narcissus: ["清冷", "優雅"],
  "water-lily": ["清透", "寧靜"],
  tiare: ["度假", "奶香"],
  praline: ["甜美", "溫暖"],
  "red-berries": ["甜美", "活潑"],
  pomelo: ["清新", "明亮"],
  // Calvin Klein notes (data/calvin-klein.ts, 2026-10-07)
  papaya: ["甜美", "活力"],
  pomegranate: ["酸甜", "活力"],
  mango: ["甜美", "度假"],
  lotus: ["平靜", "優雅"],
  orchid: ["優雅", "誘人"],
  champaca: ["溫暖", "誘人"],
  coriander: ["辛香", "清新"],
  civet: ["誘人", "成熟"],
  ozonic: ["清新", "清涼"],
  suede: ["溫潤", "成熟"],
  cocoa: ["溫暖", "甜美"],
  davana: ["溫暖", "果香"],
  olive: ["清新", "溫潤"],
  verbena: ["清新", "明亮"],
  hay: ["溫暖", "田園"],
  yuzu: ["清新", "明亮"],
  mastic: ["樹脂", "清新"],
  poppy: ["柔和", "粉感"],
  monoi: ["度假", "奶香"],
  marshmallow: ["甜美", "柔軟"],
  kulfi: ["奶香", "甜美"],
  barley: ["溫暖", "烘焙"],
  acacia: ["清新", "甜美"],
  allspice: ["辛香", "溫暖"],
  truffle: ["神秘", "大地"],
  "palo-santo": ["冥想", "溫暖"],
  "violet-leaf": ["清新", "綠意"],
  heliotrope: ["粉感", "杏仁"],
  brioche: ["奶香", "溫暖"],
  apricot: ["甜美", "溫柔"],
  "rangoon-creeper": ["甜美", "異國"],
  "sweet-pea": ["清新", "甜美"],
  sesame: ["堅果", "溫暖"],
  gurjun: ["樹脂", "溫暖"],
  cassia: ["辛香", "溫暖"],
  linen: ["潔淨", "柔軟"],
  "carrot-seed": ["大地", "溫潤"],
  guava: ["甜美", "熱帶"],
  litsea: ["清新", "明亮"],
  osmanthus: ["溫柔", "果香"],
  styrax: ["樹脂", "溫暖"],
  "fir-balsam": ["森林", "樹脂"],
  "tomato-leaf": ["綠意", "清新"],
  mugwort: ["草本", "清新"],
  "turmeric-leaf": ["辛香", "清新"],
  gentian: ["草本", "自然"],
  "green-tea": ["平靜", "清新"],
  "apple-blossom": ["清新", "溫柔"],
  amberwood: ["溫暖", "成熟"],
  fennel: ["辛香", "清新"],
  cream: ["甜美", "溫柔"],
  "brown-sugar": ["甜美", "溫暖"],
  citron: ["清新", "明亮"],
  linden: ["溫柔", "清新"],
  lilac: ["溫柔", "優雅"],
  mate: ["草本", "平靜"],
  mulberry: ["甜美", "活力"],
  medlar: ["甜美", "溫柔"],
  "almond-blossom": ["溫柔", "甜美"],
  "cherry-blossom": ["溫柔", "清新"],
  santolina: ["草本", "自然"],
  helichrysum: ["溫暖", "草本"],
  thyme: ["草本", "辛香"],
  hemp: ["草本", "神秘"],
  fir: ["自然", "平靜"],
  liquidambar: ["溫暖", "神秘"],
  "tolu-balsam": ["溫暖", "甜美"],
  "rose-stem": ["清新", "自然"],
  "ginger-lily": ["清新", "溫柔"],
  "blackcurrant-leaf": ["清新", "果香"],
  "precious-woods": ["溫暖", "神秘"],
  "ice-musk": ["清新", "乾淨"],
  "velvet-musk": ["溫柔", "平靜"],
};

const LAYER_WEIGHT = { top: 0.8, heart: 1.2, base: 1 } as const;

export interface NoteLayers {
  topNotes: readonly string[];
  heartNotes: readonly string[];
  baseNotes: readonly string[];
}

export interface WeightedTag {
  tag: string;
  weight: number;
}

/** Suggested tags from a fragrance's notes, heaviest first (heart notes count most). */
export function deriveTags({ topNotes, heartNotes, baseNotes }: NoteLayers): WeightedTag[] {
  const weights = new Map<string, number>();
  const add = (notes: readonly string[], layerWeight: number) => {
    for (const note of notes) {
      for (const tag of NOTE_TAGS[note] ?? []) weights.set(tag, (weights.get(tag) ?? 0) + layerWeight);
    }
  };
  add(topNotes, LAYER_WEIGHT.top);
  add(heartNotes, LAYER_WEIGHT.heart);
  add(baseNotes, LAYER_WEIGHT.base);
  return [...weights]
    .map(([tag, weight]) => ({ tag, weight: Math.round(weight * 100) / 100 }))
    .sort((a, b) => b.weight - a.weight || a.tag.localeCompare(b.tag));
}

const MOOD_BY_ZH = new Map(MOODS.map((m) => [m.zh, m.key]));
const MOOD_KEYS = new Set<string>(MOODS.map((m) => m.key));

/** The Mood a tag stands for, accepting either the key ("calm") or its Chinese word (平靜). */
export function tagToMood(tag: string): Mood | undefined {
  if (MOOD_KEYS.has(tag)) return tag as Mood;
  return MOOD_BY_ZH.get(tag);
}

/** Moods suggested by the notes, strongest first. */
export function deriveMoods(layers: NoteLayers, limit = 2): Mood[] {
  const moods: Mood[] = [];
  for (const { tag } of deriveTags(layers)) {
    const mood = tagToMood(tag);
    if (mood && !moods.includes(mood)) moods.push(mood);
    if (moods.length === limit) break;
  }
  return moods;
}
