import type { Fragrance } from "@/types";

/*
 * TAMBURINS perfumes from An's list (2026-10-07), checked against the official
 * pages (https://www.tamburins.com/en/shop/perfume/perfumes/): every scent is on
 * the brand's site, and its top / middle / base notes are taken from the official
 * product page — including the five An's list marked 待確認. Egg perfumes and the
 * 11 ml bottles are the same scents, so each scent is one entry with its sizes.
 * Generated by a script from the official pages.
 */
export const TAMBURINS_SOURCE = "TAMBURINS 官網（An 提供的清單，2026-10-07 依官網查證）";

const CREATED = Date.UTC(2026, 9, 7);

type Entry = Omit<Fragrance, "brand" | "origin" | "createdAt" | "tags">;

const ENTRIES: readonly Entry[] = [
  {
    id: "cat-tamburins-bottari",
    name: "Bottari",
    family: "woody",
    subFamilies: ["musky"],
    topNotes: ["akigalawood"],
    heartNotes: ["ambroxan", "ambrette"],
    baseNotes: ["ambergris", "musk", "moss"],
    description: "清新 Akigalawood、柔和苔蘚與蕈菇、琥珀麝香。官網規格：11 ml、50 ml",
  },
  {
    id: "cat-tamburins-blue-hinoki",
    name: "Blue Hinoki",
    family: "woody",
    subFamilies: ["fresh"],
    topNotes: ["pine", "bergamot", "hibiscus"],
    heartNotes: ["water", "hinoki"],
    baseNotes: ["cedar", "driftwood", "frankincense"],
    description: "清新松油、藍色檜木、漂流木。官網規格：11 ml、14 ml、50 ml（含蛋形香水）",
  },
  {
    id: "cat-tamburins-chamo",
    name: "Chamo",
    family: "floral",
    subFamilies: ["musky"],
    topNotes: ["clary-sage", "chamomile"],
    heartNotes: ["water", "cypriol"],
    baseNotes: ["amber", "musk", "blond-wood"],
    description: "濃郁洋甘菊、柔和木紋、麝香。官網規格：11 ml、14 ml、50 ml（含蛋形香水）",
  },
  {
    id: "cat-tamburins-evening-glow",
    name: "Evening Glow",
    family: "floral",
    subFamilies: ["fruity"],
    topNotes: ["lemon", "dill"],
    heartNotes: ["rose", "raspberry"],
    baseNotes: ["musk", "cypriol", "patchouli"],
    description: "夕陽玫瑰、覆盆子、麝香。官網規格：11 ml、14 ml、50 ml（含蛋形香水）",
  },
  {
    id: "cat-tamburins-summer-tails",
    name: "Summer Tails",
    family: "woody",
    subFamilies: ["floral"],
    topNotes: ["green-notes", "anise"],
    heartNotes: ["white-florals"],
    baseNotes: ["cedar", "patchouli", "musk"],
    description: "淺綠蜜風、鈴蘭、雪松木。官網規格：11 ml、50 ml",
  },
  {
    id: "cat-tamburins-white-darjeeling",
    name: "White Darjeeling",
    family: "musky",
    subFamilies: ["gourmand"],
    topNotes: ["champagne"],
    heartNotes: ["tea", "peach"],
    baseNotes: ["musk", "sandalwood"],
    description: "白香檳、大吉嶺茶、奶油麝香。官網規格：11 ml、50 ml",
  },
  {
    id: "cat-tamburins-berga-sandal",
    name: "Berga Sandal",
    family: "woody",
    subFamilies: ["citrus"],
    topNotes: ["bergamot", "lime", "cardamom"],
    heartNotes: ["cypriol", "cedar", "cucumber"],
    baseNotes: ["amyris", "sandalwood", "leather"],
    description: "地中海佛手柑、微苦綠橘、檀香。官網規格：50 ml",
  },
  {
    id: "cat-tamburins-lale",
    name: "Lale",
    family: "woody",
    subFamilies: ["floral"],
    topNotes: ["apple", "eucalyptus", "bergamot"],
    heartNotes: ["tulip", "mimosa", "sea-notes"],
    baseNotes: ["leather", "sandalwood", "musk", "coconut"],
    description: "露水青蘋果、白鬱金香、檀香。官網規格：50 ml",
  },
  {
    id: "cat-tamburins-sunshine",
    name: "Sunshine",
    family: "floral",
    subFamilies: ["woody"],
    topNotes: ["angelica", "salty-mineral"],
    heartNotes: ["lily-of-the-valley", "jasmine", "incense"],
    baseNotes: ["guaiac-wood", "cashmeran", "musk"],
    description: "白芷、鈴蘭、雲霧盔甲。官網規格：11 ml、45 ml、50 ml",
  },
  {
    id: "cat-tamburins-puppy",
    name: "Puppy",
    family: "woody",
    subFamilies: ["avantgarde"],
    topNotes: ["paw-accord", "chamomile", "aldehydes"],
    heartNotes: ["clary-sage", "myrrh"],
    baseNotes: ["cedar", "dry-wood", "ambroxan"],
    description: "堅果木、藍洋甘菊、明亮醛香。官網規格：11 ml、50 ml",
  },
  {
    id: "cat-tamburins-unknown-oud",
    name: "Unknown Oud",
    family: "woody",
    subFamilies: ["leather"],
    topNotes: ["eucalyptus", "lavender"],
    heartNotes: ["raspberry", "leather"],
    baseNotes: ["oud", "patchouli", "amber"],
    description: "尤加利、覆盆子、焦灼木材。官網規格：50 ml",
  },
  {
    id: "cat-tamburins-pumkini",
    name: "Pumkini",
    family: "gourmand",
    subFamilies: ["woody"],
    topNotes: ["bergamot", "perilla", "blood-orange"],
    heartNotes: ["pumpkin", "ginger"],
    baseNotes: ["coconut", "sandalwood", "musk"],
    description: "甜南瓜、紫蘇葉、椰奶。官網規格：50 ml",
  },
  {
    id: "cat-tamburins-late-autumn",
    name: "Late Autumn",
    family: "woody",
    subFamilies: ["fresh"],
    topNotes: ["galbanum", "buchu"],
    heartNotes: ["sugarcane", "wormwood"],
    baseNotes: ["cedar", "musk"],
    description: "苦橙、甘蔗草、麝香。官網規格：14 ml、50 ml（含蛋形香水）",
  },
  {
    id: "cat-tamburins-brown",
    name: "Brown",
    family: "woody",
    subFamilies: ["floral"],
    topNotes: ["grass", "frankincense"],
    heartNotes: ["rose", "mahogany"],
    baseNotes: ["amber", "patchouli", "oak"],
    description: "乳香、深色桃花心木、橡木。官網規格：50 ml",
  },
  {
    id: "cat-tamburins-bather-in-the-lake",
    name: "Bather In The Lake",
    family: "fougere",
    subFamilies: ["amber"],
    topNotes: ["clary-sage", "lavender"],
    heartNotes: ["wormwood", "incense", "water"],
    baseNotes: ["moss", "amber", "musk"],
    description: "艾草、霧中湖水、濕潤苔蘚。官網規格：50 ml",
  },
];

export const TAMBURINS: readonly Fragrance[] = ENTRIES.map((e) => ({
  ...e,
  brand: "TAMBURINS",
  tags: [],
  origin: "lookup",
  createdAt: CREATED,
}));
