#!/usr/bin/env python3
"""Subset 02流線形 (Ryusenkei) into web fonts split by unicode-range.

The source TTFs are ~24 MB each, far too large to ship. This script cuts them
into small WOFF2 slices and writes the matching @font-face rules, so a page
downloads only the slices whose characters it actually renders:

  slice 00  every character used in the site's own source text, plus ASCII
            and CJK punctuation — what nearly every page needs;
  slice 01+ the rest of the Big5 common-character set, in code-point chunks,
            fetched only when dynamic text (perfume names, notes) uses them.

Glyphs the font lacks fall back to Noto Serif TC via the font stack.

Usage:  python3 scripts/build-ryusenkei.py <dir containing 02Ryusenkei-*.ttf>
Needs:  pip install fonttools brotli
Re-run whenever new Chinese copy is added to the site, so slice 00 stays complete.
"""
import pathlib
import re
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "fonts" / "ryusenkei"
CSS = ROOT / "app" / "ryusenkei.css"
WEIGHTS = {"ExtraLight": 200, "Regular": 400, "Bold": 700}
CHUNK = 600


def site_characters() -> set[str]:
    text = ""
    for pattern in ("app/**/*.tsx", "app/**/*.ts", "components/**/*.tsx", "lib/**/*.ts", "data/**/*.ts"):
        for path in ROOT.glob(pattern):
            text += path.read_text(encoding="utf-8")
    return {c for c in text if ord(c) >= 0x2000}


def big5_common() -> set[str]:
    chars = set()
    for hi in range(0xA4, 0xC7):
        for lo in [*range(0x40, 0x7F), *range(0xA1, 0xFF)]:
            try:
                chars.add(bytes([hi, lo]).decode("big5"))
            except UnicodeDecodeError:
                pass
    return chars


def unicode_range(codepoints: list[int]) -> str:
    """Collapse sorted code points into CSS unicode-range syntax."""
    parts, start, prev = [], None, None
    for cp in sorted(codepoints):
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            parts.append((start, prev))
            start = prev = cp
    if start is not None:
        parts.append((start, prev))
    return ", ".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in parts)


def main() -> None:
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if not src or not src.is_dir():
        sys.exit(__doc__)

    cmap = TTFont(src / "02Ryusenkei-Regular.ttf", lazy=True).getBestCmap()
    basic = set(range(0x20, 0x7F)) | set(range(0x3000, 0x3040)) | set(range(0xFF01, 0xFF5F)) | set(range(0x2010, 0x2070))
    primary = sorted(cp for cp in basic | {ord(c) for c in site_characters()} if cp in cmap)
    rest = sorted(cp for cp in {ord(c) for c in big5_common()} if cp in cmap and cp not in set(primary))
    slices = [primary] + [rest[i : i + CHUNK] for i in range(0, len(rest), CHUNK)]

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.woff2"):
        old.unlink()

    rules = [
        "/* Generated by scripts/build-ryusenkei.py — do not edit by hand. */",
        "/* 02流線形 (Ryusenkei) by Flop Design, derived from Source Han Serif. SIL OFL 1.1 — see public/fonts/ryusenkei/LICENSE_OFL.txt */",
    ]
    for style, weight in WEIGHTS.items():
        font_path = src / f"02Ryusenkei-{style}.ttf"
        for index, codepoints in enumerate(slices):
            name = f"ryusenkei-{weight}-{index:02d}.woff2"
            options = subset.Options()
            options.flavor = "woff2"
            options.layout_features = ["*"]
            options.name_IDs = ["*"]
            options.notdef_outline = True
            options.hinting = False
            font = subset.load_font(str(font_path), options)
            subsetter = subset.Subsetter(options)
            subsetter.populate(unicodes=codepoints)
            subsetter.subset(font)
            subset.save_font(font, str(OUT / name), options)
            rules.append(
                "@font-face {\n"
                '  font-family: "Ryusenkei";\n'
                f'  src: url("/fonts/ryusenkei/{name}") format("woff2");\n'
                f"  font-weight: {weight};\n"
                "  font-style: normal;\n"
                "  font-display: swap;\n"
                f"  unicode-range: {unicode_range(codepoints)};\n"
                "}"
            )
            print(f"{name}: {len(codepoints)} chars, {(OUT / name).stat().st_size // 1024} KB")

    (OUT / "LICENSE_OFL.txt").write_bytes((src / "LICENSE_OFL.txt").read_bytes())
    CSS.write_text("\n".join(rules) + "\n", encoding="utf-8")
    print(f"wrote {CSS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
